Comment import tests
Commenting for now since this fails :
import: 'napari_cellseg3d'
import: 'napari_cellseg3d.res'
import: 'napari_cellseg3d.plugins'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/napari-cellseg3d_1702627458019/test_tmp/run_test.py", line 8, in <module>
    import napari_cellseg3d.plugins
  File "/home/conda/feedstock_root/build_artifacts/napari-cellseg3d_1702627458019/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari_cellseg3d/plugins.py", line 5, in <module>
    from napari_cellseg3d.code_plugins.plugin_helper import Helper
  File "/home/conda/feedstock_root/build_artifacts/napari-cellseg3d_1702627458019/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari_cellseg3d/code_plugins/plugin_helper.py", line 9, in <module>
    from qtpy.QtCore import QSize
  File "/home/conda/feedstock_root/build_artifacts/napari-cellseg3d_1702627458019/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/qtpy/__init__.py", line 287, in <module>
    raise QtBindingsNotFoundError from None
qtpy.QtBindingsNotFoundError: No Qt bindings could be found